CREATE TABLE user_details (
   id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   email VARCHAR(50) NOT NULL,
   firstName varchar(255) DEFAULT NULL,
   password varchar(255) DEFAULT NULL,
   token varchar(255),
   created DATE,
   modified DATE,
   active BOOLEAN DEFAULT TRUE NOT NULL
);
